#steps:
#- name: 'gcr.io/cloud-builders/mvn'
 # args: ['install', '-P', 'test']
  #dir: 'HelloWorld'
# TODO setup Apigee account secret using encrypted variables
steps:
- name: 'gcr.io/cloud-builders/mvn'
  entrypoint: 'bash'
  args: ['-c', 'mvn apigee-enterprise:deploy -Ptest -Dusername=maheshdevops88@gmail.com -Dpassword=$$password']
  dir: 'HelloWorld'
  secretEnv: ['PASSWORD']


secrets:
- kmsKeyName: projects/true-source-244117/locations/global/keyRings/password/cryptoKeys/password
  secretEnv:
    PASSWORD: CiQAZy74ThjvQ+qOzUaAHVmIuJjUwnjgElTDmoAzHkjozbnGp0cSMwACTr7sPuV8lO2i23NCzSlIPpXbGElIQI+Np3hMcAPtc8HaQTc1EA+M81XFrITKFjrdmw==
